using System.Globalization;

namespace VelaShell.Plugin.S3;

/// <summary>
/// 插件自带的文案表。插件的国际化由自己负责(SDK 只给 <c>context.Host.Locale</c> 与
/// <c>LocaleChanged</c> 事件),因此这些词条随插件走 —— 它们本就是 S3 的领域词汇,
/// 留在宿主的 <c>Strings.resx</c> 里只会让宿主替一个自己并不认识的协议背词典。
/// <para>
/// 只带简体中文与英文两套:宿主支持五种语言,但插件文案量大且专业词多,
/// 缺哪种语言就回落英文,而不是显示一个键名。
/// </para>
/// </summary>
/// <param name="locale">宿主当前语言(如 <c>zh-Hans</c>、<c>en</c>)。</param>
public sealed class Loc(string locale)
{
    private readonly bool _chinese = locale.StartsWith("zh", StringComparison.OrdinalIgnoreCase);

    /// <summary>取一条文案;未收录的键原样返回(方便一眼看出漏了哪条)。</summary>
    /// <param name="key">文案键。</param>
    /// <returns>文案。</returns>
    public string this[string key] =>
        (_chinese ? Chinese : English).TryGetValue(key, out string? value) ? value : key;

    /// <summary>取一条文案(<see cref="this[string]" /> 的具名形式,便于在表达式里连用)。</summary>
    /// <param name="key">文案键。</param>
    /// <returns>文案。</returns>
    public string Get(string key) => this[key];

    /// <summary>取一条带占位符的文案并格式化。</summary>
    /// <param name="key">文案键。</param>
    /// <param name="args">占位参数。</param>
    /// <returns>格式化后的文案。</returns>
    public string Format(string key, params object?[] args) =>
        string.Format(CultureInfo.CurrentCulture, this[key], args);

    private static readonly Dictionary<string, string> English = new(StringComparer.Ordinal)
    {
        // 连接表单
        ["S3_Endpoint"] = "Endpoint",
        ["S3_EndpointHint"] = "Host name or a full URL (https://minio.internal:9000). The scheme and port are taken from the URL when present.",
        ["S3_AccessKeyId"] = "Access Key ID",
        ["S3_SecretAccessKey"] = "Secret Access Key",
        ["S3_Region"] = "Region",
        ["S3_RegionHint"] = "Used for the SigV4 signature only; most non-AWS implementations accept us-east-1.",
        ["S3_Addressing"] = "Addressing style",
        ["S3_AddressingHint"] = "Auto uses virtual-hosted only for AWS endpoints; self-hosted MinIO/Ceph need path style.",
        ["S3_AddressingAuto"] = "Automatic",
        ["S3_AddressingPath"] = "Path style",
        ["S3_AddressingVirtual"] = "Virtual hosted",
        ["S3_UseTls"] = "Use HTTPS",
        ["S3_PlaintextWarn"] = "Plain HTTP: credentials stay protected by the signature, but object contents travel in the clear.",
        ["S3_DefaultBucket"] = "Default bucket",
        ["S3_DefaultBucketHint"] = "Optional. Required for accounts that may only access one bucket — those cannot call ListBuckets.",
        ["S3_SessionToken"] = "Session token",
        ["S3_SessionTokenHint"] = "For temporary STS credentials; leave empty for long-lived keys.",
        ["S3_PartSize"] = "Part size (bytes)",
        ["S3_Concurrency"] = "Concurrent parts",
        ["S3_StorageClass"] = "Storage class",
        ["S3_ServerSideEncryption"] = "Server-side encryption",
        ["S3_ShowFolderMarkers"] = "Show folder placeholder objects",
        // 右键动作
        ["S3_PresignedUrl"] = "Copy share link",
        ["S3_PresignedUrlCopied"] = "Share link copied to the clipboard.",
        ["S3Obj_Manage"] = "S3 object…",
        ["S3Obj_BucketManager"] = "Bucket manager…",
        // 桶管理器
        ["S3Mgr_Title"] = "Bucket: {0}",
        ["S3Mgr_Overview"] = "Overview",
        ["S3Mgr_Versions"] = "Object versions",
        ["S3Mgr_MultipartUploads"] = "Incomplete uploads",
        ["S3Msg_NotConfigured"] = "Not configured yet.",
        ["S3Msg_NotSupported"] = "This server does not support this configuration.",
        // 桶配置项
        ["S3Cfg_Versioning"] = "Versioning",
        ["S3Cfg_PublicAccessBlock"] = "Block public access",
        ["S3Cfg_Ownership"] = "Object ownership",
        ["S3Cfg_Encryption"] = "Default encryption",
        ["S3Cfg_ObjectLock"] = "Object lock",
        ["S3Cfg_Tagging"] = "Tags",
        ["S3Cfg_Website"] = "Static website",
        ["S3Cfg_Logging"] = "Access logging",
        ["S3Cfg_Accelerate"] = "Transfer acceleration",
        ["S3Cfg_RequestPayment"] = "Requester pays",
        ["S3Cfg_Lifecycle"] = "Lifecycle rules",
        ["S3Cfg_Policy"] = "Bucket policy",
        ["S3Cfg_Acl"] = "Bucket ACL",
        ["S3Cfg_Cors"] = "CORS",
        ["S3Cfg_Replication"] = "Replication",
        ["S3Cfg_Notification"] = "Event notifications",
        ["S3Cfg_Inventory"] = "Inventory",
        ["S3Cfg_Analytics"] = "Analytics",
        ["S3Cfg_Metrics"] = "Request metrics",
        ["S3Cfg_IntelligentTiering"] = "Intelligent tiering",
        ["S3Cfg_MetadataTable"] = "Metadata tables",
        ["S3Cfg_Abac"] = "ABAC",
        // 桶配置表单字段、概览、版本列表与操作反馈
        ["Size"] = "Size",
        ["Modified"] = "Modified",
        ["S3Obj_Title"] = "Object: {0}",
        ["S3Obj_Applied"] = "Applied.",
        ["S3Obj_StorageClass"] = "Storage class",
        ["S3Obj_Restore"] = "Restore",
        ["S3Obj_RestoreRequested"] = "Restore requested; the object becomes downloadable once the retrieval finishes.",
        ["S3Msg_Saved"] = "Saved.",
        ["S3Msg_Deleted"] = "Deleted.",
        ["S3Msg_NoNamedConfigs"] = "No named configurations on this bucket.",
        ["S3Msg_NoVersions"] = "No versions under this prefix.",
        ["S3Msg_NoUploads"] = "No incomplete multipart uploads.",
        ["S3Msg_UploadsFound"] = "{0} incomplete upload(s). Unaborted parts keep being billed.",
        ["S3Msg_UploadAborted"] = "Upload aborted.",
        ["S3Msg_VersionDeleted"] = "Version deleted permanently.",
        ["S3Msg_VersionRestored"] = "Version restored as the current one (implemented as a copy).",
        ["S3Ovw_Bucket"] = "Bucket",
        ["S3Ovw_Region"] = "Region",
        ["S3Ovw_Versioning"] = "Versioning",
        ["S3Ovw_ObjectLock"] = "Object lock",
        ["S3Ovw_PublicAccess"] = "Public access",
        ["S3Ovw_Enabled"] = "enabled",
        ["S3Ovw_Disabled"] = "disabled",
        ["S3Ovw_Public"] = "public",
        ["S3Ovw_NotPublic"] = "not public",
        ["S3Ovw_Unknown"] = "unknown",
        ["S3Ver_Key"] = "Key",
        ["S3Ver_VersionId"] = "Version id",
        ["S3Ver_Latest"] = "current",
        ["S3Ver_Historical"] = "historical",
        ["S3Ver_DeleteMarker"] = "delete marker",
        ["S3Fld_VersioningStatus"] = "Versioning status",
        ["S3Fld_VersioningHint"] = "Enabled keeps every version; Suspended stops creating new ones but keeps the existing history.",
        ["S3Fld_MfaDelete"] = "MFA delete",
        ["S3Fld_MfaDeleteHint"] = "Requires an MFA device to delete versions; can only be changed by the bucket owner's root account.",
        ["S3Fld_BlockPublicAcls"] = "Block public ACLs",
        ["S3Fld_IgnorePublicAcls"] = "Ignore public ACLs",
        ["S3Fld_BlockPublicPolicy"] = "Block public bucket policies",
        ["S3Fld_RestrictPublicBuckets"] = "Restrict public buckets",
        ["S3Fld_ObjectOwnership"] = "Object ownership",
        ["S3Fld_ObjectOwnershipHint"] = "BucketOwnerEnforced disables ACLs entirely — the recommended setting for new buckets.",
        ["S3Fld_EncryptionAlgorithm"] = "Encryption algorithm",
        ["S3Fld_EncryptionAlgorithmHint"] = "AES256 = SSE-S3; aws:kms = SSE-KMS (needs a key id below).",
        ["S3Fld_KmsKeyId"] = "KMS key id",
        ["S3Fld_KmsKeyIdHint"] = "Only used with aws:kms; leave empty for the account default key.",
        ["S3Fld_BucketKey"] = "S3 Bucket Key",
        ["S3Fld_BucketKeyHint"] = "Cuts KMS request cost for SSE-KMS buckets.",
        ["S3Fld_ObjectLockEnabled"] = "Object lock enabled",
        ["S3Fld_ObjectLockEnabledHint"] = "Can only be turned on when the bucket is created; versioning is required.",
        ["S3Fld_RetentionMode"] = "Default retention mode",
        ["S3Fld_RetentionModeHint"] = "COMPLIANCE cannot be shortened or removed by anyone, including the root account.",
        ["S3Fld_RetentionDays"] = "Retention days",
        ["S3Fld_RetentionYears"] = "Retention years",
        ["S3Fld_Tags"] = "Tags",
        ["S3Fld_TagsHint"] = "Bucket tags are used for cost allocation and policy conditions.",
        ["S3Fld_IndexDocument"] = "Index document",
        ["S3Fld_IndexDocumentHint"] = "Served for requests that address a directory, e.g. index.html.",
        ["S3Fld_ErrorDocument"] = "Error document",
        ["S3Fld_LogTargetBucket"] = "Log target bucket",
        ["S3Fld_LogTargetBucketHint"] = "Must be in the same region; leave empty to disable access logging.",
        ["S3Fld_LogTargetPrefix"] = "Log key prefix",
        ["S3Fld_AccelerateStatus"] = "Acceleration status",
        ["S3Fld_AccelerateHint"] = "Transfers go through the CloudFront edge network; AWS only, and it is billed separately.",
        ["S3Fld_Payer"] = "Request payer",
        ["S3Fld_PayerHint"] = "Requester means the caller pays for requests and egress — they must opt in explicitly.",
    };

    private static readonly Dictionary<string, string> Chinese = new(StringComparer.Ordinal)
    {
        ["S3_Endpoint"] = "服务端点",
        ["S3_EndpointHint"] = "主机名,或一整条 URL(https://minio.internal:9000);带协议与端口时以 URL 为准。",
        ["S3_AccessKeyId"] = "Access Key ID",
        ["S3_SecretAccessKey"] = "Secret Access Key",
        ["S3_Region"] = "区域",
        ["S3_RegionHint"] = "仅用于 SigV4 签名;非 AWS 的实现基本都接受 us-east-1。",
        ["S3_Addressing"] = "寻址方式",
        ["S3_AddressingHint"] = "自动 = 只对 AWS 端点用虚拟主机式;自建 MinIO / Ceph 需要路径式。",
        ["S3_AddressingAuto"] = "自动",
        ["S3_AddressingPath"] = "路径式",
        ["S3_AddressingVirtual"] = "虚拟主机式",
        ["S3_UseTls"] = "使用 HTTPS",
        ["S3_PlaintextWarn"] = "明文 HTTP:密钥仍受签名保护,但对象内容会以明文传输。",
        ["S3_DefaultBucket"] = "默认桶",
        ["S3_DefaultBucketHint"] = "可留空。只授予单桶权限的账号必须填 —— 那种账号调 ListBuckets 会被拒。",
        ["S3_SessionToken"] = "会话令牌",
        ["S3_SessionTokenHint"] = "STS 临时凭据用;长期密钥留空。",
        ["S3_PartSize"] = "分片大小(字节)",
        ["S3_Concurrency"] = "并发分片数",
        ["S3_StorageClass"] = "存储类别",
        ["S3_ServerSideEncryption"] = "服务端加密",
        ["S3_ShowFolderMarkers"] = "显示目录占位符对象",
        ["S3_PresignedUrl"] = "复制分享链接",
        ["S3_PresignedUrlCopied"] = "分享链接已复制到剪贴板。",
        ["S3Obj_Manage"] = "S3 对象管理…",
        ["S3Obj_BucketManager"] = "桶管理…",
        ["S3Mgr_Title"] = "桶:{0}",
        ["S3Mgr_Overview"] = "概览",
        ["S3Mgr_Versions"] = "对象版本",
        ["S3Mgr_MultipartUploads"] = "未完成分片上传",
        ["S3Msg_NotConfigured"] = "尚未配置。",
        ["S3Msg_NotSupported"] = "该服务端不支持这项配置。",
        ["S3Cfg_Versioning"] = "版本控制",
        ["S3Cfg_PublicAccessBlock"] = "阻止公共访问",
        ["S3Cfg_Ownership"] = "对象所有权",
        ["S3Cfg_Encryption"] = "默认加密",
        ["S3Cfg_ObjectLock"] = "对象锁定",
        ["S3Cfg_Tagging"] = "标签",
        ["S3Cfg_Website"] = "静态网站托管",
        ["S3Cfg_Logging"] = "访问日志",
        ["S3Cfg_Accelerate"] = "传输加速",
        ["S3Cfg_RequestPayment"] = "请求者付费",
        ["S3Cfg_Lifecycle"] = "生命周期规则",
        ["S3Cfg_Policy"] = "桶策略",
        ["S3Cfg_Acl"] = "桶 ACL",
        ["S3Cfg_Cors"] = "跨域规则",
        ["S3Cfg_Replication"] = "跨区域复制",
        ["S3Cfg_Notification"] = "事件通知",
        ["S3Cfg_Inventory"] = "清单",
        ["S3Cfg_Analytics"] = "分析",
        ["S3Cfg_Metrics"] = "请求指标",
        ["S3Cfg_IntelligentTiering"] = "智能分层",
        ["S3Cfg_MetadataTable"] = "元数据表",
        ["S3Cfg_Abac"] = "ABAC",
        ["Size"] = "大小",
        ["Modified"] = "修改时间",
        ["S3Obj_Title"] = "对象:{0}",
        ["S3Obj_Applied"] = "已应用。",
        ["S3Obj_StorageClass"] = "存储类别",
        ["S3Obj_Restore"] = "取回",
        ["S3Obj_RestoreRequested"] = "已发起取回;取回完成后该对象才可下载。",
        ["S3Msg_Saved"] = "已保存。",
        ["S3Msg_Deleted"] = "已删除。",
        ["S3Msg_NoNamedConfigs"] = "该桶没有具名配置。",
        ["S3Msg_NoVersions"] = "该前缀下没有版本。",
        ["S3Msg_NoUploads"] = "没有未完成的分片上传。",
        ["S3Msg_UploadsFound"] = "有 {0} 个未完成的分片上传。未中止的分片会一直计费。",
        ["S3Msg_UploadAborted"] = "已中止该分片上传。",
        ["S3Msg_VersionDeleted"] = "该版本已被永久删除。",
        ["S3Msg_VersionRestored"] = "已把该版本恢复为当前版本(以复制实现)。",
        ["S3Ovw_Bucket"] = "桶",
        ["S3Ovw_Region"] = "区域",
        ["S3Ovw_Versioning"] = "版本控制",
        ["S3Ovw_ObjectLock"] = "对象锁定",
        ["S3Ovw_PublicAccess"] = "公共访问",
        ["S3Ovw_Enabled"] = "已启用",
        ["S3Ovw_Disabled"] = "未启用",
        ["S3Ovw_Public"] = "公开",
        ["S3Ovw_NotPublic"] = "非公开",
        ["S3Ovw_Unknown"] = "未知",
        ["S3Ver_Key"] = "对象键",
        ["S3Ver_VersionId"] = "版本 id",
        ["S3Ver_Latest"] = "当前版本",
        ["S3Ver_Historical"] = "历史版本",
        ["S3Ver_DeleteMarker"] = "删除标记",
        ["S3Fld_VersioningStatus"] = "版本控制状态",
        ["S3Fld_VersioningHint"] = "Enabled 保留每一个版本;Suspended 停止产生新版本,但已有历史仍在。",
        ["S3Fld_MfaDelete"] = "MFA 删除",
        ["S3Fld_MfaDeleteHint"] = "删除版本需要 MFA 设备;只能由桶属主的根账号更改。",
        ["S3Fld_BlockPublicAcls"] = "阻止公共 ACL",
        ["S3Fld_IgnorePublicAcls"] = "忽略公共 ACL",
        ["S3Fld_BlockPublicPolicy"] = "阻止公共桶策略",
        ["S3Fld_RestrictPublicBuckets"] = "限制公共桶",
        ["S3Fld_ObjectOwnership"] = "对象所有权",
        ["S3Fld_ObjectOwnershipHint"] = "BucketOwnerEnforced 会整体停用 ACL —— 新建桶推荐这一项。",
        ["S3Fld_EncryptionAlgorithm"] = "加密算法",
        ["S3Fld_EncryptionAlgorithmHint"] = "AES256 = SSE-S3;aws:kms = SSE-KMS(需在下面填密钥 id)。",
        ["S3Fld_KmsKeyId"] = "KMS 密钥 id",
        ["S3Fld_KmsKeyIdHint"] = "仅 aws:kms 时使用;留空即用账号默认密钥。",
        ["S3Fld_BucketKey"] = "S3 Bucket Key",
        ["S3Fld_BucketKeyHint"] = "为 SSE-KMS 桶降低 KMS 请求开销。",
        ["S3Fld_ObjectLockEnabled"] = "启用对象锁定",
        ["S3Fld_ObjectLockEnabledHint"] = "只能在建桶时开启,且要求已开版本控制。",
        ["S3Fld_RetentionMode"] = "默认保留模式",
        ["S3Fld_RetentionModeHint"] = "COMPLIANCE 模式下任何人(含根账号)都无法缩短或解除保留。",
        ["S3Fld_RetentionDays"] = "保留天数",
        ["S3Fld_RetentionYears"] = "保留年数",
        ["S3Fld_Tags"] = "标签",
        ["S3Fld_TagsHint"] = "桶标签用于成本分摊与策略条件。",
        ["S3Fld_IndexDocument"] = "索引文档",
        ["S3Fld_IndexDocumentHint"] = "访问目录形式的地址时返回它,如 index.html。",
        ["S3Fld_ErrorDocument"] = "错误文档",
        ["S3Fld_LogTargetBucket"] = "日志目标桶",
        ["S3Fld_LogTargetBucketHint"] = "必须与本桶同区域;留空即关闭访问日志。",
        ["S3Fld_LogTargetPrefix"] = "日志键前缀",
        ["S3Fld_AccelerateStatus"] = "加速状态",
        ["S3Fld_AccelerateHint"] = "传输经 CloudFront 边缘网络;仅 AWS 提供,且单独计费。",
        ["S3Fld_Payer"] = "请求付费方",
        ["S3Fld_PayerHint"] = "Requester 表示由调用方承担请求与流出费用 —— 对方必须显式声明接受。",
    };
}
